"""The one key the Key Management Module deliberately does not manage.

Every other key in this system is generated by key_manager, wrapped under
the server master key, and stored. This one is never stored at all: the
private scalar is re-derived from the user's password whenever it is
needed and discarded immediately. The database therefore holds no value --
wrapped or otherwise -- from which a message can be recovered, which is
what allows these messages to be called end-to-end.

The salt here is separate from the password salt, and the derivation is
domain-separated with a label. Were both the same, the derived private
scalar would be byte-identical to the stored password hash: the private
key would sit in the database in plaintext.
"""
from app.crypto.ecc_service import G, N, scalar_mult
from app.crypto.kdf import pbkdf2
from app.crypto.random_gen import random_bytes

SALT_BYTES = 16
LABEL = b"land-record-messaging-key|"


def new_salt() -> str:
    return random_bytes(SALT_BYTES).hex()


def derive_private(password: str, salt: str, iterations: int) -> dict:
    """Re-derive the messaging private key. Never stored, never logged."""
    material = pbkdf2(password, LABEL + bytes.fromhex(salt), iterations)

    # Map 32 bytes into [1, N-1]. secp256k1's N is within 2**-128 of 2**256,
    # so the bias from this reduction is far below any practical threshold.
    return {"d": int.from_bytes(material, "big") % (N - 1) + 1}


def derive_public(password: str, salt: str, iterations: int) -> dict:
    """The public point for a password. The scalar is discarded on return."""
    return {"Q": scalar_mult(derive_private(password, salt, iterations)["d"], G)}